<?php
/**
 * ChinaTown - LAMP SaaS FrameWork.
 * Complete User Registration and Management. Secure, Fast, Small and Light.
 *
 * THIS CODE ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 *
 * PHP version 5.4
 *
 * @version    HG: <5.1.1>
 * @category   SaaS RAD LAMP FrameWork.
 * @see        https://ampae.com/chinatown/
 * @author     AMPAE <info@ampae.com>
 * @license    https://ampae.com/chinatown/license.txt
 * @copyright  2009 - 2019 AMPAE
**/

namespace Ampae\Lib;

class Model
{
    public $results = array(); // Used to store results generated by Models
    public $config = array(); // Used to store configuration data
    public $appinfo = array(); // Used to store application info
    public $redirect = null;

    /**
     * constructor.
     */
    public function __construct()
    {
        global $controller;
//        $this->appinfo['domain'] = $controller->info['domain'];
        $this->appinfo['url'] = $controller->info['url'];
        $this->appinfo['content_flag'] = null;

        if ($controller->argc > APP_URL_MAX_LEVEL) {
            $this->redirect = $this->appinfo['url'];
        }
    }

    /**
     * Set data to eXchange; same keys will be overwritten
     * Usage: $model->set( KEY, VALUE );
     * Get: $value = $model->results[KEY];.
     *
     * @param string $k config
     * @param string $v config
     */
    public function set($k, $v)
    {
        $this->results[$k] = $v;
    }

    /**
     * Set data to eXchange; allows multiple keys
     * Usage: $model->add( KEY, VALUE );
     * Get: $value = $model->results[KEY];.
     *
     * @param string $k config
     * @param string $v config
     */
    public function add($k, $v)
    {
        $this->results[$k][] = $v;
    }

    // --- !!! !!!

    public function getTheme()
    {
        //TODO: to database !!!
        $this->appinfo['theme_vendor']      = DEF_VENDOR;
        $this->appinfo['theme_directory']   = DEF_THEME;
        $this->appinfo['theme_path']        = DIR_APP.DIRECTORY_SEPARATOR.$this->appinfo['theme_vendor'].DIRECTORY_SEPARATOR.DIR_THEMES.DIRECTORY_SEPARATOR.$this->appinfo['theme_directory'];
        $this->appinfo['theme_webpath']     = DIR_APP.'/'.$this->appinfo['theme_vendor'].'/'.DIR_THEMES.'/'.$this->appinfo['theme_directory'];
    }

    // ---

    public function load($file)
    {
        global $session, $sign, $controller, $model, $view, $local;

        $ret = false;

        $tmpPage = realpath($file);

        if (file_exists($tmpPage)) {
            include $tmpPage;
            $ret = true;
        }

        return $ret;
    }
}
